export const transactions = [
    {
      id: '1',
      type: 'topup',
      title: 'Wallet Top up',
      time: '10:10',
      amount: 10100,
      status: 'success',
    },
    {
      id: '2',
      type: 'charge',
      title: 'Delivery Charges',
      time: '16:23',
      amount: -3100,
      status: 'success',
    },
    {
      id: '3',
      type: 'charge',
      title: 'Delivery Charges',
      time: 'Yesterday 9:30',
      amount: -2700,
      status: 'success',
    },
    {
      id: '4',
      type: 'topup',
      title: 'Wallet Top up',
      time: 'Yesterday 16:23',
      amount: 36000,
      status: 'failed',
    },
    {
      id: '5',
      type: 'charge',
      title: 'Delivery Charges',
      time: 'Mar 17, 2025 16:23',
      amount: -3100,
      status: 'success',
    },
    {
      id: '6',
      type: 'charge',
      title: 'Delivery Charges',
      time: 'Mar 17, 2025 16:23',
      amount: -2700,
      status: 'success',
    },
    {
      id: '7',
      type: 'topup',
      title: 'Wallet Top up',
      time: 'Mar 16, 2025 16:23',
      amount: 36000,
      status: 'success',
    },
    {
      id: '8',
      type: 'topup',
      title: 'Wallet Top up',
      time: '16:23',
      amount: 36000,
      status: 'success',
    },
  ];